### PR TITLE
fix: update footer layout to align items to the start

### LINKED ISSUE #2: Footer column (Past Events & Quick Links ) alignment
Past Events & Quick Links are centered in mobile view, but they should be aligned to the left with the other column.

### PR DESCRIPTION
**Pull request by sahilpatel09**
@Solankimimoh Please review the change for column alignment.

Fixes #2

### CODE REVIEW

File: src/components/layout/Footer.tsx [hunk 1]
```diff
@@ -66,7 +66,7 @@ export default function Footer() {
 
         <motion.div
           variants={containerVariants}
-          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-9 mb-16 justify-items-center"
+          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-9 mb-16 justify-items-start"
```
Comment (Solankimimoh) [inline src/components/layout/Footer.tsx]: @sahilpatel09  Can we set the start property for mobile and center for medium or desktop?

Comment (Solankimimoh) [reply src/components/layout/Footer.tsx]: LGTM
